version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8080:8080"
    volumes:
      - ./descriptions/api.github.com/api.github.com.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml